import type { Metadata } from "next";
import {inter} from "@/components/blog/fonts";
import "./globals.css";
import {AuthProvider} from './AuthProvider';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="bg-white text-black min-h-screen " style={inter.style}>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
